config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :words do
    resources :synonyms
    resources :notes
    resources :examples
  end

  resources :types

  get 'masonry', to: 'pages#masonry'
  get 'creation', to: 'pages#creation'
  get 'rating', to: 'pages#rating'
  get 'index', to: 'words#index'
  root "words#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/example.rb
class Example < ApplicationRecord
  belongs_to :word
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :word
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/synonym.rb
class Synonym < ApplicationRecord
  belongs_to :word
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :word_types
  has_many :words, through: :word_types
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  ratyrate_rater
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :types, through: :word_types
  has_many :word_types
  has_many :synonyms, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :examples, dependent: :destroy
  ratyrate_rateable 'visual_effects', 'original_score', 'director', 'custome_design'
  ratyrate_rater
end

app/models/word_type.rb
class WordType < ActiveRecord::Base
  belongs_to :word
  belongs_to :type
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def create
    @word = Word.find(params[:word_id])
    @example = @word.examples.create(example_params)
    redirect_to word_path(@word)
  end

  def destroy
    @word = Word.find(params[:word_id])
    @example = @word.examples.find(params[:id])
    @example.destroy
    redirect_to word_path(@word)
  end

  private
    def example_params
      params.require(:example).permit(:body)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @word = Word.find(params[:word_id])
    @note = @word.notes.create(note_params)
    redirect_to word_path(@word)
  end

  def destroy
    @word = Word.find(params[:word_id])
    @note = @word.notes.find(params[:id])
    @note.destroy
    redirect_to word_path(@word)
  end

  private
    def note_params
      params.require(:note).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def masonry
  end

  def creation
  end

  def rating
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
  end

  def new
    @type = Type.new
  end

  def create
    @type = Type.new(type_params)
    @type.save

      redirect_to types_path
  end

  def edit
    @type = Type.find(params[:id])
  end

  def update
    @type = Type.find(params[:id])
    @type.update(type_params)
    redirect_to types_path(@type)

  end

  def show
    @type = Type.find(params[:id])
  end
  private
  def type_params
    params.require(:type).permit(:name)
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    @words = Word.all.order('created_at DESC')
  end

  def new
    @word = Word.new
  end

  def edit
    @word = Word.find(params[:id])

  end

  def create
    @word = Word.new(word_params)

    @word.save
    redirect_to @word
  end

  def update
    @word = Word.find(params[:id])
    @word.update(word_params)
    redirect_to word_path(@word)
  end

  def show
    @word = Word.find(params[:id])
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to root_path
  end

  private
  def word_params
    params.require(:word).permit(:title, :chinese, :pinyin, :meaning, :exampleUsage, type_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/synonyms_helper.rb
module SynonymsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/edit.html.erb
<div class="wrapper">
  <div class="wrapper-form">
    <%= form_for(@word, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <%= f.collection_check_boxes :type_ids, Type.all, :id, :name do |cb| %>
          <%= cb.label(class: "checkbox-inline input_checkbox"){cb.check_box(class: "checkbox") + cb.text} %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.text_field :title, class: "form-control", placeholder: "Title", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.text_field :chinese, class: "form-control", placeholder: "chinese", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.text_field :pinyin, class: "form-control", placeholder: "pinyin", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.text_area :meaning, rows: 2, class: "form-control", placeholder: "meaning" %>
      </div>
      <div class="form-group">
        <%= f.text_area :exampleUsage, rows: 2, class: "form-control", placeholder: "example" %>
      </div>
      <div class="form-group">
        <%= f.number_field :funny, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-primary btn-lg' %>
      </div>
    <% end %>
    <%= link_to "Cancel request and return to articles listing", words_path %>
  </div>
</div>

app/views/words/index.html.erb
  <div class="grid">
    <% @words.each do |word| %>
      <% if word.title == "test1" %>
        <div class="grid-item"><p><%= link_to word.title, word_path(word) %></p></div>
      <% elsif word.title == "test2"%>
        <div class="grid-item grid-item--width3"><p><%= link_to word.title, word_path(word) %></p></div>
      <% elsif word.title == "test3"%>
        <div class="grid-item grid-item--height2"><p><%= link_to word.title, word_path(word) %></p></div>
      <% elsif word.title == "test4"%>
        <div class="grid-item grid-item--height3"><p><%= link_to word.title, word_path(word) %></p></div>
      <% elsif word.title == "test5"%>
        <div class="grid-item grid-item--width4"><p><%= link_to word.title, word_path(word) %></p></div>
      <% else %>
        <div class="grid-item grid-item--width2"><p><%= link_to word.title, word_path(word) %></p></div>
      <% end %>
    <% end %>

  </div>








  <ul>
    <% @words.each do |word| %>
      <% if word.title == "BJ4" %>
        <li class="item_wrapper_1"><%= link_to word.title, word_path(word) %></li>
      <% else %>
        <li class="item_wrapper"><%= link_to word.title, word_path(word) %></li>
      <% end %>
    <% end %>
  </ul>




<script>
// external js: masonry.pkgd.js

var grid = document.querySelector('.grid');
var msnry = new Masonry( grid, {
  columnWidth: 160
});

grid.addEventListener( 'click', function( event ) {
  // don't proceed if item was not clicked on
  if ( !matchesSelector( event.target, '.grid-item' ) ) {
    return;
  }
  // change size of item via class
  event.target.classList.toggle('grid-item--gigante');
  // trigger layout
  msnry.layout();
});

</script>

app/views/words/new.html.erb
<div class="wrapper">
  <div class="wrapper-form">
    <%= form_for :word, url: words_path do |f| %>
      <div class="form-group">
        <%= f.collection_check_boxes :type_ids, Type.all, :id, :name do |cb| %>
          <%= cb.label(class: "checkbox-inline input_checkbox"){cb.check_box(class: "checkbox") + cb.text} %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.text_field :title, class: "form-control", placeholder: "Title", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.text_field :chinese, class: "form-control", placeholder: "chinese", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.text_field :pinyin, class: "form-control", placeholder: "pinyin", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.text_area :meaning, rows: 2, class: "form-control", placeholder: "meaning" %>
      </div>
      <div class="form-group">
        <%= f.text_area :exampleUsage, rows: 2, class: "form-control", placeholder: "example" %>
      </div>
      <div class="form-group">
        <%= f.number_field :funny, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-primary btn-lg' %>
      </div>
    <% end %>
  </div>
</div>

app/views/words/show.html.erb
<div class="wrapper">
<div class="popupContainer container">
  <div class="card-wrapper row">
    <div class="card-header col-md-12">
      <span><strong>Chinese to English</strong></span>
      <hr>
    </div>
      <div class="main-content col-md-6">
        <section class="word-card">
          <div class="section_1"><span><%= @word.title %></span></div>
        </section>
        <section class="section_2">
          <p class="section_2_title item-label">Note</p>
          <div id="notes">
            <%= render @word.notes %>
          </div>

          <div class="add_button">
              <div class="add"><i class="fa fa-plus"></i></div>
              <div class="content">
                <%= render "notes/form" %>
              </div>
          </div>
        </section>

        <hr>
        <section class="section_3">
          <p class="section_2_title item-label">Example</p>
          <div id="examples">
            <%= render @word.examples %>
          </div>

          <div class="add_button">
              <div class="add"><i class="fa fa-plus"></i></div>
              <div class="content">
                <%= render "examples/form" %>
              </div>
          </div>

        </section>

      </div>
      <div class="side-content col-md-6">
        <div class="word-info">
          <ul class="word-list">
            <li class="item-label">Pinyin</li>
            <li class="item"><%= @word.pinyin %></li>
            <hr>
            <li class="item-label">Meaning</li>
            <li class="item"><%= @word.meaning %></li>
            <hr>
            <li class="item-label">Funny</li>
            <li>
              <nav>
                <li class="scale_item scale_item_click"></li>
                <li class="scale_item scale_item_click"></li>
                <li class="scale_item scale_item_click"></li>
                <li class="scale_item scale_item_click"></li>
                <li class="scale_item"></li>
              </nav>
            </li>
            <br><br>
            <li class="item-label">Useful</li>
            <li>
              <nav>
                <li class="scale_item scale_item_click"></li>
                <li class="scale_item scale_item_click"></li>
                <li class="scale_item scale_item_click"></li>
                <li class="scale_item"></li>
                <li class="scale_item"></li>
              </nav>
            </li>
          <hr>
          </ul>
        </div>
        <div class="card-buttons">
          <div class="card-button button-like"><span>Like</span></div>
          <div class="card-button button-copy"><span>Copy</span></div>
        </div>
        <hr>
        <div class="word-info">
          <ul class="word-list">
            <li class="item-label">Synonym</li>


            <li class="item-label">Popular</li>

            <% Word.all.each do |word| %>
              <li class="list_item"><%= link_to "##{word.title}", word_path(word) %> &nbsp;&nbsp;</li>
            <% end %>

          </ul>
        </div>
      </div>

  </div>
</div>


















<%= link_to "Edit this word", edit_word_path(@word), class: "btn btn-xs btn-primary" %>
<%= link_to "Delete this word", word_path(@word), method: :delete,
                                        data: { confirm: "Are you sure you want to delete the word?"},
                                        class: "btn btn-xs btn-danger" %>
</div>


<script>
$(".add").click(function () {

    $header = $(this);
    //getting the next element
    $content = $header.next();
    //open up the content needed - toggle the slide- if visible, slide up, if not slidedown.
    $content.slideToggle(500, function () {
        //execute this after slideToggle is done
        //change text of header based on visibility of content div
    });

});
</script>